spring.application.name=StudentManagementwithloginlogout
spring.application.name=student-management-system

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
# Default administrator (override with environment variables if needed)
app.admin.email=admin@example.com
app.admin.password=Admin@123
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
