package com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.controlller;
import java.util.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.audit.AuditService; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.document.DocumentService; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.entity.*; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.repository.*; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.service.ContractService; import com.StudentManagementwithloginlogout.StudentManagementwithloginlogout.version.ContractVersionService;
@RestController @RequestMapping("/api/contracts") public class ContractController { @Autowired ContractService service; @Autowired ContractRepository repo; @Autowired AuditService audit; @Autowired ContractVersionService versions; @Autowired DocumentService docs; @Autowired ModificationRequestRepository requests; @Autowired ObjectMapper mapper;
 @PostMapping public Contract add(@RequestBody Contract c){Contract x=service.addContract(c); versions.snapshot(x); audit.log("CREATE","CONTRACT",x.getId(),"Contract created"); return x;}
 @GetMapping public Page<Contract> all(@RequestParam(defaultValue="") String q,@RequestParam(required=false) ContractStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size){Pageable p=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by("id").descending()); if(status!=null&&!q.isBlank())return repo.findByContractNameContainingIgnoreCaseAndStatus(q,status,p); if(status!=null)return repo.findByStatus(status,p); if(!q.isBlank())return repo.findByContractNameContainingIgnoreCase(q,p); return repo.findAll(p);}
 @GetMapping("/{id}") public Contract get(@PathVariable Long id){return service.getContractById(id);}
 @PutMapping("/{id}") public Contract update(@PathVariable Long id,@RequestBody Contract c){Contract x=service.updateContract(id,c); versions.snapshot(x); audit.log("UPDATE","CONTRACT",id,"Contract updated"); return x;}
 @DeleteMapping("/{id}") public String delete(@PathVariable Long id){service.deleteContract(id); audit.log("DELETE","CONTRACT",id,"Contract deleted"); return "Contract Deleted Successfully";}
 @GetMapping("/{id}/versions") public List<ContractVersion> versions(@PathVariable Long id){return versions.history(id);}
 @PostMapping("/{id}/documents") public ContractDocument upload(@PathVariable Long id,@RequestParam MultipartFile file) throws Exception {ContractDocument d=docs.upload(id,file); audit.log("CREATE","DOCUMENT",d.getId(),"Document uploaded for contract "+id); return d;}
 @GetMapping("/{id}/documents") public List<ContractDocument> documents(@PathVariable Long id){return docs.list(id);}
 @GetMapping("/documents/{docId}") public ResponseEntity<byte[]> document(@PathVariable Long docId){ContractDocument d=docs.get(docId); MediaType t; try{t=d.getContentType()==null?MediaType.APPLICATION_OCTET_STREAM:MediaType.parseMediaType(d.getContentType());}catch(Exception e){t=MediaType.APPLICATION_OCTET_STREAM;} return ResponseEntity.ok().contentType(t).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+d.getFileName().replace("\"","")+"\"").body(d.getData());}
 @PostMapping("/{id}/modifications") public ModificationRequest request(@PathVariable Long id,@RequestBody String data){Contract c=repo.findById(id).orElseThrow(()->new IllegalArgumentException("Contract not found")); Object u=org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(); jakarta.servlet.http.HttpSession s=((org.springframework.web.context.request.ServletRequestAttributes)u).getRequest().getSession(); Object lu=s.getAttribute("loggedUser"); String by=lu instanceof User?((User)lu).getEmail():"UNKNOWN"; ModificationRequest r=requests.save(new ModificationRequest(c,data,by)); audit.log("CREATE","MODIFICATION_REQUEST",r.getId(),"Modification requested"); return r;}
 @GetMapping("/modifications/pending") public List<ModificationRequest> pending(){return requests.findByStatusOrderByRequestedAtDesc("PENDING");}
 @PostMapping("/modifications/{id}/approve") public ModificationRequest approve(@PathVariable Long id){ModificationRequest r=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found")); if(!"PENDING".equals(r.getStatus())) throw new IllegalStateException("Request already reviewed"); try { JsonNode n=mapper.readTree(r.getRequestedData()); Contract c=r.getContract(); if(n.has("contractName")) c.setContractName(n.get("contractName").asText()); if(n.has("description")) c.setDescription(n.get("description").asText()); if(n.has("partyName")) c.setPartyName(n.get("partyName").asText()); if(n.has("startDate")) c.setStartDate(java.time.LocalDate.parse(n.get("startDate").asText())); if(n.has("endDate")) c.setEndDate(java.time.LocalDate.parse(n.get("endDate").asText())); if(n.has("status")) c.setStatus(ContractStatus.valueOf(n.get("status").asText().toUpperCase())); repo.save(c); versions.snapshot(c); } catch(Exception e){throw new IllegalArgumentException("Invalid modification data: use JSON contract fields",e);} r.setStatus("APPROVED"); r.setReviewedAt(java.time.LocalDateTime.now()); r.setReviewedBy("ADMIN"); requests.save(r); audit.log("UPDATE","MODIFICATION_REQUEST",id,"Modification approved and new contract version created"); return r;}
 @PostMapping("/modifications/{id}/reject") public ModificationRequest reject(@PathVariable Long id){ModificationRequest r=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found")); r.setStatus("REJECTED"); r.setReviewedAt(java.time.LocalDateTime.now()); r.setReviewedBy("ADMIN"); return requests.save(r);}
}
